#define   LINUX      1                /* Linux specific parts. Ver 7.1 */
#define   SLOWSTACK  0                /*procedural stack manipulation*/
#define   DSTACK     1                /*dynamic resizable stack*/
#define   BITF       0                /*bit fields are used in ID space*/
#define   TRACEABLE  1                /* controls some trace parts */
#define   DEBUG      0                /* For indoor developement use only! */  
