#define   IBMPC      0                /*IBM PC */
#define   LATTICE    0                /*IBM PC Lattice C compiler*/
#define   SLOWSTACK  0                /*procedural stack manipulation*/
#define   DSTACK     1                /*dynamic resizable stack*/
#define   BITF       0                /*bit fields are used in ID space*/
#define   _TURBOC_   0                /*PC Borland Turbo C compiler specific */
#define   TRACEABLE  1                /* controls some trace parts */
#define   DEBUG      0                /* For indoor developement use only! */  
